[
  # "google-cloud-sdk"
  "google-drive"
  "iterm2"
  "karabiner-elements"
  "remarkable"
  "visual-studio-code"
  "whatsapp"
  "telegram"
  "zoom"
  "yubico-authenticator"
  "yubico-yubikey-manager"
  "spotify"
  "tradingview"
  "raycast"
  "cursor"
  "microsoft-word"
  "microsoft-excel"
  "microsoft-powerpoint"
  "microsoft-outlook"
  "microsoft-teams"
  "onedrive"
  # "brave-browser"
  # "brave-browser@beta"
  # "brave-browser@nightly"
  "google-chrome"
  "google-chrome@beta"
  "google-chrome@dev"
  # "HazeOver"
  "devpod"
  # "aerospace"
  "Syncthing"
  "QSyncthingTray"
  "ghostty"
  "mouseless"
  "nucleo"
  "bitwarden"
  # "keycastr"
  # "bartender"
  "calibre"
  # "ollama"
  "granola"
  "alt-tab"
  "claude"
  "claude-code"
  "mattt/tap/iMCP"
  "mattt/tap/Companion"
]
  